# Generated by Django 3.1.4 on 2022-08-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220729_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author',
            new_name='author_id',
        ),
    ]
