# Generated by Django 3.1.4 on 2022-08-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20220809_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('restricted', 'restricted'), ('all', 'all')], default='restricted', max_length=50)),
                ('role', models.CharField(choices=[('author', 'author'), ('responsable', 'responsable'), ('Contributor', 'Contributor')], default='', max_length=128)),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
