# Generated by Django 4.0.5 on 2022-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('author', 'author'), ('responsable', 'responsable'), ('contributor', 'contributor')], default='', max_length=128),
        ),
    ]
